"""Add unique constraint for order model

Revision ID: 14ca4f37991a
Revises: a5ffa3d49281
Create Date: 2022-03-14 18:00:00.546345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ca4f37991a'
down_revision = 'a5ffa3d49281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_order_job_material', 'order', ['material_sku', 'job_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_order_job_material', 'order', type_='unique')
    # ### end Alembic commands ###
