"""Update Order pk

Revision ID: 1bc43b30c1ab
Revises: cb3953b9e6a3
Create Date: 2022-03-12 16:17:05.433092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc43b30c1ab'
down_revision = 'cb3953b9e6a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'material_sku',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('order', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_order_id', table_name='order')
    op.drop_column('order', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_order_id', 'order', ['id'], unique=False)
    op.alter_column('order', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order', 'material_sku',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
