"""Add total-price column on Order model

Revision ID: 378782cfb9b9
Revises: d7970429d419
Create Date: 2022-03-12 12:48:25.011636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '378782cfb9b9'
down_revision = 'd7970429d419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('total_price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'total_price')
    # ### end Alembic commands ###
