"""Add autogenerate keys

Revision ID: a5ffa3d49281
Revises: 1bc43b30c1ab
Create Date: 2022-03-12 18:48:02.008434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ffa3d49281'
down_revision = '1bc43b30c1ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
