"""Add material model

Revision ID: f0febe8404fb
Revises: 66647fbe6d21
Create Date: 2022-03-10 14:37:02.460623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0febe8404fb'
down_revision = '66647fbe6d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material',
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('sku')
    )
    op.create_index(op.f('ix_material_name'), 'material', ['name'], unique=False)
    op.create_index(op.f('ix_material_sku'), 'material', ['sku'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_sku'), table_name='material')
    op.drop_index(op.f('ix_material_name'), table_name='material')
    op.drop_table('material')
    # ### end Alembic commands ###
